services:
  grafana:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'

  otel-collector:
    image: 'otel/opentelemetry-collector-contrib:latest'
    volumes:
      - './otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro'
    ports:
      - '4317:4317'
      - '4318:4318'
    depends_on:
      - grafana
