receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: basic
  otlphttp/lgtm:
    endpoint: http://grafana:4318

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug, otlphttp/lgtm ]
    metrics:
      receivers: [ otlp ]
      exporters: [ debug, otlphttp/lgtm ]
    logs:
      receivers: [ otlp ]
      exporters: [ debug, otlphttp/lgtm ]
